feat
shilin-anton/thinknetica_rails pull request #2
Opened 2022-08-21 11:23 UTC by shilin-anton

project reconfigured for postgreSQL,
needed migrations added

2022-08-21 17:10 UTC, BubuntuClu requested changes

2022-08-21 17:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20220821103038_create_questions.rb
> +      t.integer :test_id
нужно указать что это внешний ключ

2022-08-21 17:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20220821091055_create_tests.rb
> +      t.integer :category_id
нужно указать что это внешний ключ. посмотри операцию `t.references`

2022-08-21 17:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20220821103157_create_answers.rb
> +      t.integer :question_id
нужно указать что это внешний ключ

2022-08-21 17:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20220821103157_create_answers.rb
> +      t.integer :user_id
такая связь не потребуется, можешь удалить

2022-08-21 17:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20220821103254_create_users.rb
> +      t.integer :score
что за очки? почему они в пользователе лежат?

2022-08-21 17:10 UTC, BubuntuClu commented on TestGuru/db/migrate/20220821103540_add_constraint_to_user.rb
> +  def up
почему бы это не указать при создании таблицы, через опцию для поля, чтобы не плодить на каждое поле отдельную миграцию?

2022-08-22 19:18 UTC, shilin-anton commented on TestGuru/db/migrate/20220821103254_create_users.rb
> +      t.integer :score
общее кол-во заработанных очков за все тесты?

2022-08-22 19:38 UTC, closed without merging