task complete
shilin-anton/thinknetica_rails pull request #7
Opened 2022-10-21 16:59 UTC by shilin-anton

2022-10-22 05:39 UTC, VidgarVii requested changes

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/controllers/questions_controller.rb
> +
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо условие записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/controllers/questions_controller.rb
> +    redirect_to action: :index, test_id: test_id
чтобы сделать редирект достаточно работать с объектом, а не с его атрибутами
`redirect_to @question.test`

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/controllers/questions_controller.rb
> +  end
Очень странное решение
чтобы если ресурс не найден, то принято выкидывать 404
StandardError это 500 ошибка сервера
Чтобы всё работало корректно надо использоваться метод find для поиска, а не find_by

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/controllers/questions_controller.rb
> +  before_action :find_questions, only: :index
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/controllers/questions_controller.rb
> +    render :index
если хочешь, чтобы показалось хтмл страница, то не надо писать render :index
просто в методе определяешь инстанс переменные, которые хочешь отобразить во вью

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/controllers/questions_controller.rb
> +    render :new
тоже самое. render :new тут лишний

2022-10-22 05:39 UTC, VidgarVii commented on TestGuru/app/views/questions/index.html.erb
> +</table>
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-11-07 09:33 UTC, shilin-anton commented on TestGuru/app/controllers/questions_controller.rb
> +    redirect_to action: :index, test_id: test_id
а как обратиться к @question.test если я перед этим делаю @question.destroy?

2022-11-07 17:10 UTC, BubuntuClu commented on TestGuru/app/controllers/questions_controller.rb
> +    find_questions
`@quetions = test.questions`

2022-11-07 17:15 UTC, merged

2022-11-07 17:19 UTC, shilin-anton commented on TestGuru/app/controllers/questions_controller.rb
> +    find_questions
ok :)