task cmpleted
shilin-anton/thinknetica_rails pull request #8
Opened 2022-11-17 15:47 UTC by shilin-anton

2022-11-17 17:35 UTC, BubuntuClu requested changes

2022-11-17 17:35 UTC, BubuntuClu commented on TestGuru/app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :id)
`id` сюда не надо передавать, ты его не обновляешь

2022-11-17 17:35 UTC, BubuntuClu commented on TestGuru/app/controllers/questions_controller.rb
> +  def update; end
а где реализация метода?

2022-11-17 17:35 UTC, BubuntuClu commented on TestGuru/app/controllers/tests_controller.rb
> +  def destroy; end
где реализация?

2022-11-17 17:35 UTC, BubuntuClu commented on TestGuru/app/controllers/tests_controller.rb
> +    params.require(:test).permit(:title, :id, :category_id, :level)
`id` тут не надо размещать

2022-11-18 08:07 UTC, shilin-anton commented on TestGuru/app/controllers/tests_controller.rb
> +  def destroy; end
прошу прощения, что-то я совсем забыл..

2022-11-19 17:44 UTC, merged